Improve job file writing

diff --git a/GMX_replicater b/GMX_replicater
--- a/GMX_replicater
+++ b/GMX_replicater
@@ -2,8 +2,8 @@
 
 # File: GMX_replicater
 # Description : Build and launch a sequential equilibration and production job in GROMACS
-# Version : 1.4
-# Last update : 01-02-2022
+# Version : 1.5
+# Last update : 31-03-2022
 
 #######################################################################
 ##                          GMX_replicater                           ##
@@ -16,7 +16,7 @@
 
 ##  DEFAULT VARIABLES  ################################################
 
-  __version__='1.3'
+  __version__='1.5'
 
   nodes_def=1                       # number of nodes (only of SLURM)
   cores_def=8                       # number of cores / parallel enviroment
@@ -182,68 +182,67 @@ for replica in ${replica_list[@]}; do
 
   ## write .job file
   jobname="${name}.job"
-  echo "#!/bin/bash"                          >  ${jobname}
-  echo ""                                     >> ${jobname} ## SGE ######################
-  echo "#$ -N ${name}"                        >> ${jobname} # Job name
-  echo "#$ -e $msgf/${name}.msg"              >> ${jobname} # Error mesages path
-  echo "#$ -o $msgf/${name}.msg"              >> ${jobname} # Output mesages path
-  echo "#$ -q $queue_sge"                     >> ${jobname} # Queue name
-  echo "#$ -R yes"                            >> ${jobname} # Reservation enabled
-  if [ "$cores" != '1' ]; then
-    echo "#$ -pe mp$cores $cores"             >> ${jobname} # Parallel environment (cores)
-  fi
-  echo ""                                     >> ${jobname} ## SLURM ####################
-  echo "#SBATCH -J ${name}"                   >> ${jobname} # Job name
-  echo "#SBATCH -e $msgf/${name}.msg"         >> ${jobname} # Error mesages path
-  echo "#SBATCH -o $msgf/${name}.msg"         >> ${jobname} # Output mesages path
-  echo "#SBATCH -p ${queue_slurm}"            >> ${jobname} # Queue name
-  echo "#SBATCH -N ${nodes}"                  >> ${jobname} # nodes
-  echo "#SBATCH --ntasks-per-node=${cores}"   >> ${jobname} # cores
-  echo "#SBATCH --mem=${memory}"              >> ${jobname} # memory
-  if [ "$queue_slurm" == 'gpu' ]; then
-    echo "#SBATCH --gres=gpu:${gpus}"         >> ${jobname} # GPUs
-  fi
-  echo ""                                     >> ${jobname}
+  printf "#!/bin/bash\n\n" > ${jobname}
+  {
+    # SGE -------------------------------------------------------------
+    echo "#$ -N ${name}"                         # Job name
+    echo "#$ -e $msgf/${name}.msg"               # Error mesages path
+    echo "#$ -o $msgf/${name}.msg"               # Output mesages path
+    echo "#$ -q $queue_sge"                      # Queue name
+    echo "#$ -R yes"                             # Reservation enabled
+    echo "#$ -cwd"                               # Run in current working directory
+    if [ "$cores" != '1' ]; then
+      echo "#$ -pe mp$cores $cores"              # Parallel environment (cores)
+    fi
+    echo ""
+    # SLURM -----------------------------------------------------------
+    echo "#SBATCH -J ${name}"                    # Job name
+    echo "#SBATCH -e $msgf/${name}.msg"          # Error mesages path
+    echo "#SBATCH -o $msgf/${name}.msg"          # Output mesages path
+    echo "#SBATCH -p ${queue_slurm}"             # Queue name
+    echo "#SBATCH -N ${nodes}"                   # nodes
+    echo "#SBATCH --ntasks-per-node=${cores}"    # cores
+    echo "#SBATCH --mem=${memory}"               # memory
+    if [ "$queue_slurm" == 'gpu' ]; then
+      echo "#SBATCH --gres=gpu:${gpus}"          # GPUs
+    fi
+    echo ""
 
-  # modules
-  for mod in ${modules[@]}; do
-    echo "module load $mod"                   >> ${jobname}
-  done
-  echo ""                                     >> ${jobname}
-
-  echo "cd $origin"                           >> ${jobname}
-  echo ""                                     >> ${jobname}
-
-  unset equi_prev
-  crd=$coord
-
-  # equilibration
-  if [ ! -z "$equi_mdp" ]; then
-    for equi in ${equi_mdp[@]}; do
-      equi_name=${equi##*/}; equi_name=${equi_name%.*}${replica}
-      echo -n "$executable grompp -v -p $topol -c $crd -r $crd -f $equi -o ${equi_name}.tpr $index" >> ${jobname}
-      # use checkpoint if not the first run
-      if [ ! -z "$equi_prev" ]; then
-        echo -n " -t ${equi_prev}.cpt" >> ${jobname}
-      fi
-      echo "" >> ${jobname}
-      echo "mpirun -np $(($nodes * $cores)) $executable mdrun -s ${equi_name}.tpr -deffnm ${equi_name}" >> ${jobname}
-      crd=${equi_name}.gro
-      equi_prev=${equi_name}
-      echo "" >> ${jobname}
+    # modules
+    for mod in ${modules[@]}; do
+      echo "module load $mod"
     done
-  else
-    echo "WARNING: No equilibration specified. Skipping equilibration."
-  fi
 
-  # production
-  echo -n "$executable grompp -v -p $topol -c $crd -r $crd -f $prod_mdp -o ${name}.tpr $index" >> ${jobname}
-  # use checkpoint if not the first run
-  if [ ! -z "$equi_prev" ]; then
-    echo -n " -t ${equi_prev}.cpt" >> ${jobname}
-  fi
-  echo "" >> ${jobname}
-  echo "mpirun -np $(($nodes * $cores)) $executable mdrun -s ${name}.tpr -deffnm ${name}" >> ${jobname}
+    printf "\ncd $origin \n\n"
+
+    unset equi_prev
+    crd=$coord
+
+    # equilibration
+    if [ ! -z "$equi_mdp" ]; then
+      for equi in ${equi_mdp[@]}; do
+        equi_name=${equi##*/}; equi_name=${equi_name%.*}${replica}
+        printf "$executable grompp -v -p $topol -c $crd -r $crd -f $equi -o ${equi_name}.tpr $index"
+        # use checkpoint if not the first run
+        if [ ! -z "$equi_prev" ]; then
+          printf " -t ${equi_prev}.cpt"
+        fi
+        printf "\nmpirun -np $(($nodes * $cores)) $executable mdrun -s ${equi_name}.tpr -deffnm ${equi_name} \n\n"
+        crd=${equi_name}.gro
+        equi_prev=${equi_name}
+      done
+    else
+      echo "WARNING: No equilibration specified. Skipping this step." >&2
+    fi
+
+    # production
+    printf "$executable grompp -v -p $topol -c $crd -r $crd -f $prod_mdp -o ${name}.tpr $index"
+    # use checkpoint if not the first run
+    if [ ! -z "$equi_prev" ]; then
+      printf " -t ${equi_prev}.cpt"
+    fi
+    printf "\nmpirun -np $(($nodes * $cores)) $executable mdrun -s ${name}.tpr -deffnm ${name} \n"
+  } >> ${jobname}
 
   ## launch
   if [ "$dry_flg" == "true" ]; then
